config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :purchases
  end

  devise_for :users
  root 'categories#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  protected

  def initialize(user)
    user ||= User.new
    can :read, :all
    can :create, :all

    return unless user.present?

    can :manage, User, id: user.id
    can :manage, Category, user_id: user.id
    can :manage, Purchase, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :purchases, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
  def total_purchases
    purchases.size
  end

  def total_purchases_amount
    purchases.sum(:amount)
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :name, presence: true
  validates :amount, presence: true
  validates :category_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :purchases, dependent: :destroy
  has_many :catagories, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = %i[name email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.where(user_id: current_user.id).order('created_at DESC')
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
    @icons = icons
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon, :user_id)
  end

  def icons
    { 'Shopping' => 'icon-1.png', 'Education' => 'icon-2.jpg', 'Transportation' => 'icon-3.png',
      'Food' => 'icon-4.jpg', 'Entertainment' => 'icon-5.png', 'Health' => 'icon-6.jpg',
      'Bills' => 'icon-7.png', 'Other' => 'icon-8.jpg' }
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /purchases or /purchases.json
  def index
    @purchases = Purchase.where(user_id: current_user.id, category_id: params[:category_id]).order('created_at DESC')
  end

  # GET /purchases/1 or /purchases/1.json
  def show; end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit; end

  # POST /purchases or /purchases.json
  def create
    @category = Category.find(params[:category_id])
    @purchase = Purchase.new(purchase_params)
    @purchase.user_id = current_user.id
    @purchase.category_id = params[:category_id]

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to category_purchases_path(@category), notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1 or /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to purchase_url(@purchase), notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1 or /purchases/1.json
  def destroy
    @category = Category.find(params[:category_id])
    @purchase = Purchase.find(params[:id])
    @purchase.destroy

    respond_to do |format|
      format.html { redirect_to category_purchases_path(@category), notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_purchase
    @purchase = Purchase.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def purchase_params
    params.require(:purchase).permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<table class="table">
<tbody>
<tr class="category-table">
<td scope="col"><%=image_tag "#{category.icon}" , class: "img" %></td>
<td scope="col"><strong><%= link_to category.name , category_purchases_path(category_id: category.id) , class: "nav-link text-black" %><strong></td>
<td scope="col"><%= category.total_purchases %></td>
<td scope="col"> $<%= category.total_purchases_amount %></td>
<td scope="col">

 <%= button_to 'Remove',
      category_path(category),method: :delete,
      class: "btn btn-danger" %> </td>

</tr>
</tbody>
</table>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-outline mb-3">
    <%= form.text_field :name,  required: true,  class:"form-control", placeholder: "Name"%><br>
  </div>

<div class="form-outline mb-3">
    <%= form.select :icon, options_for_select([
      ['Shopping' , @icons['Shopping']],
      ['Food' , @icons['Food']],
      ['Transport' , @icons['Transportation']],
      ['Entertainment' , @icons['Entertainment']],
      ['Health' , @icons['Health']],
      ['Education' , @icons['Education']],
      ['Bills' , @icons['Bills']],
      ['Other' , @icons['Other']]
    ]), {include_blank: 'Select Icon'} , required: true , class: "form-select" %>
  </div>

 <%= form.hidden_field :user_id, value: current_user.id %>

 
    <%= form.submit "Add Category", class: "btn btn-success"%>

<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<% if user_signed_in? %>
     <%= render partial: 'shared/header_categories' %>
  
     <%end%>
<div class="container">
        <%# <div class="card shadow-2-strong" style="border-radius: 1rem;"> %>

<div class="header-contents">
<h1 class="header">Categories</h1>
<%= link_to fa_icon("plus"), new_category_path, class: "btn btn-primary add-button"%>
</div>
<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>

</div>
 
<%# </div> %>
</div>

app/views/categories/new.html.erb
<div class="container py-5 h-100">
<div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
<div class="header-new">
<%= link_to fa_icon("arrow-left"), categories_path %>
<h1 class="header">New category</h1>
</div>
<%= render "form", category: @category %>

<br>


</div>
    </div>
        </div>
        </div>
    </div>

app/views/categories/show.html.erb
<div class="container">

<%= render @category %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/ac19a35571.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     
    
    <%= yield %>
  </body>
</html>

app/views/purchases/_form.html.erb
<%= form_with(model: purchase, url: {action: "create"}) do |form| %>
    <% if purchase.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>
        <ul>
          <% purchase.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div class="form-outline mb-3">
      <%= form.text_field :name, type: "text", placeholder: "name", class: "form-control" %><br />
      </div>
      <div class="form-outline mb-3">

      <%= form.text_field :amount, type: "number", placeholder: "Amount", class: "form-control" %><br />
             </div>
    
      <%= form.submit "Add Purchase" , class: "btn btn-success"%>
    
       
   <% end %>

  

app/views/purchases/_purchase.html.erb
<tr>
  <td ><%= purchase.name %></td>
  <td>$<%= purchase.amount %></td>
  <td > <%= purchase.category.name %></td>
  <td >

      <%= button_to "Delete", category_purchase_path(purchase.category_id, purchase.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </td>
    <p class="total text-center">total amount =$<%= purchase.amount %></p>

</tr>



 

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render "form", purchase: @purchase %>

<br>

<div>
  <%= link_to "Show this purchase", @purchase %> |
  <%= link_to "Back to purchases", purchases_path %>
</div>

app/views/purchases/index.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>
<div>
<h1 class="header">Purchases</h1>

<%= link_to "New purchase", new_category_purchase_path  ,class: "btn btn-info"%>
</div>
  <div id="purchases">
        <%= render 'shared/purchase_table' do %>
          <% @purchases.each do |purchase| %>
            <%= render purchase %>
          <% end %>
        <% end %>
      </div>

      </div>

app/views/purchases/new.html.erb
<div class="container py-5 h-100">
<div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
<div class="header-new">
<%= link_to fa_icon("arrow-left"), category_purchases_path %>
<h1 class="header">New purchase</h1>

</div>
<%= render "form", purchase: @purchase %>
  
  </div>
  </div>
  </div>
  </div>
  </div>

app/views/purchases/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @purchase %>

<div>
  <%= link_to "Edit this purchase", edit_category_purchase_path(@purchase) %> |
  <%= link_to "Back to purchases", category_purchases_path %>

</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-info mt-4" role="alert">
<%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-warning mt-4" role="alert">
 <%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_header_categories.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #3778c2;">
  <div class="container-fluid">
    <ul class="navbar-nav">
       <% if user_signed_in? %>
       
          <li class="nav-item">
            <%= link_to "Categories" , categories_path, class: "nav-link" %>
          </li>

         <%end%>

      </ul>
      
       <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if user_signed_in? %>
      
         <li class="nav-item">
          <%= button_to "Sign Out" , destroy_user_session_path, method: :delete, data: { turbo: false } , class: "btn btn-warning"%>
         </li>
      <%else%>
         <li class="nav-item">
          <%= link_to "Sign Up" , new_user_registration_path, class: "nav-link"%>
         </li>
         <li class="nav-item">
          <%= link_to "Sign In" , new_user_session_path , class: "nav-link" %>
         </li>
      
      <%end%>
       </ul>
  </div>
</nav>
    <%= render partial: 'shared/flash' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #3778c2;">
  <div class="container-fluid">
  
  <%= link_to "Budget App" , root_path , class: "navbar-brand" %>
    <ul class="navbar-nav">
       <% if user_signed_in? %>
       
          <li class="nav-item">
            <%= link_to "Budget App" , categories_path, class: "nav-link" %>
          </li>
         <%end%>
      </ul>
      
       <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if user_signed_in? %>
      
         <li class="nav-item">
          <%= button_to "Sign Out" , destroy_user_session_path, method: :delete, data: { turbo: false } , class: "btn btn-warning"%>
         </li>
      <%else%>
         <li class="nav-item">
          <%= link_to "Sign Up" , new_user_registration_path, class: "nav-link"%>
         </li>
         <li class="nav-item">
          <%= link_to "Sign In" , new_user_session_path , class: "nav-link" %>
         </li>
      
      <%end%>
       </ul>
  </div>
</nav>

app/views/shared/_purchase_table.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Amount</th>
      <th scope="col">Category</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= yield%>
  </tbody>
</table>

<%= link_to fa_icon("arrow-left") , categories_path , class: "btn btn-dark"%>
   

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>